// This file is auto-generated by scripts/generate-env.js
// Do not edit this file directly. It will be overwritten.
// Set environment variables and run 'npm run generate-env' to regenerate this file.

export const environment = {
  production: false,
  msal: {
    clientId: '7073e7f0-71e1-4969-a4a8-732ff0d162c2',
    authority: 'https://dngextnp.b2clogin.com/dngextnp.onmicrosoft.com/B2C_1_login_dime_app',
    redirectUri: 'http://localhost:4200',
    postLogoutRedirectUri: 'http://localhost:4200',
    knownAuthorities: ['dngextnp.b2clogin.com']
  }
};
